
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: tRHZswuk0pr6
      POSTGRES_DB: verceldb   
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U default -d verceldb'"]
      interval: 2s
      timeout: 3s
      retries: 3
  mailhog:
        container_name: e2e_mailhog
        image: mailhog/mailhog:latest
        ports:
            - '8025:8025'
            - '1025:1025'
        environment:
            MH_STORAGE: maildir
            MH_MAILDIR_PATH: /tmp
        volumes:
            - maildir:/tmp
        entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]
        #command: -invite-jim=1 -jim-accept=0.50
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: /bin/sh -c " /usr/bin/mc alias set myminio http://minio:9000 root password && /usr/bin/mc mb myminio/image --region=ap-northeast-1 && /usr/bin/mc anonymous set public myminio/image && /usr/bin/mc anonymous set download myminio/image"  
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
        createbuckets:
          condition: service_started
        db:
          condition: service_healthy
        mailhog:
          condition: service_started
        minio:
          condition: service_started
    volumes:
      - ./playwright/e2e:/app/playwright
    environment:
      NEXTAUTH_SECRET: GENERATE-A-GOOD-SECRET
      NEXTAUTH_URL: http://localhost:3001/
      NEXT_PUBLIC_SITE_URL: http://localhost:3001/
      POSTGRES_URL: postgres://default:tRHZswuk0pr6@db:5432/verceldb
      POSTGRES_PRISMA_URL: postgres://default:tRHZswuk0pr6@db:5432/verceldb
      POSTGRES_URL_NO_SSL: postgres://default:tRHZswuk0pr6@db:5432/verceldb
      POSTGRES_URL_NON_POOLING: postgres://default:tRHZswuk0pr6@db:5432/verceldb
      POSTGRES_USER: default
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: tRHZswuk0pr6
      POSTGRES_DATABASE: verceldb
      POSTGRES_PORT: 5433
      S3_ENDPOINT: "minio"
      S3_PORT: 9000
      S3_ACCESS_KEY: "root"
      S3_SECRET_KEY: "password"
      S3_BUCKET_NAME: "image"
      S3_USE_SSL: false
      S3_TESTMODE: true
      IMAGE_PUBLIC_URL: "http://minio:9000"

      AUTH_SECRET: 548d5c9b7127725e56e0810b9f9ba6b8
      EMAIL_SERVER_HOST: mailhog
      EMAIL_SERVER_PORT: 1025
      EMAIL_SERVER_USER: user
      EMAIL_SERVER_PASSWORD: password
      EMAIL_FROM: olaf@ojkaas.nl
    ports:
      - "3001:3001"
volumes:
  maildir: {}